### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [rafaelstz/magento-boaspraticas#5]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by rafaelstz** [comment]
Olá @codehangen, está sim, fique a vontade para contribuir. Obrigado!

**Comment by ghost** [comment]
Oi rafaelstz.

> Olá @codehangen, está sim, fique a vontade para contribuir. Obrigado!

fico feliz com seu comentário e quero ajudar muito esse projeto. Vou fechar essa issue, você respondeu minha dúvida.

*tenha um ótimo e valeu pela paciência em responder minha dúvida*
